# Generated by Django 4.2.30 on 2026-09-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horaire',
            old_name='heure_arrivee',
            new_name='heure_limite_retard',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='horaire',
        ),
        migrations.RemoveField(
            model_name='horaire',
            name='heure_depart',
        ),
        migrations.RemoveField(
            model_name='horaire',
            name='heure_depart_midi',
        ),
        migrations.RemoveField(
            model_name='horaire',
            name='heure_retour',
        ),
        migrations.RemoveField(
            model_name='horaire',
            name='tolerance_retard_minutes',
        ),
        migrations.RemoveField(
            model_name='horaire',
            name='type',
        ),
        migrations.AddField(
            model_name='employe',
            name='type_journee',
            field=models.CharField(choices=[('NORMAL', 'Journée normale'), ('CONTINU', 'Journée continue')], default='NORMAL', max_length=10),
        ),
    ]
