# Generated by Django 4.2.30 on 2026-09-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0004_make_employe_email_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='type_journee',
            field=models.CharField(choices=[('CONTINU', 'Journée continue')], default='CONTINU', max_length=10),
        ),
    ]
